### ISSUE TITLE
Porting to LF 7.1

### ISSUE THREAD

**Issue by giovanni-ciganotto** [smclab/liferay-eu-cookie-agreement#1]
Development must be compatible with any release of Liferay 7.1, therefore:

- CE from GA1 to GA3
- DXP from fixpack 0 to fixpack 8

**Comment by samueledonato** [comment]
Completed test in Liferay 7.1 CE/DXP. 
Tested in following version:
- Liferay CE GA1/GA2/GA3
- Liferay DXP fixpack 1/5/8
